services:

  app:
    build:
      context: .
      dockerfile: /docker/spring_boot/Dockerfile
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    command: sh ./docker/spring_boot/start.sh
    ports:
      - 8080:8080
      - 35729:35729 # Port 35729 allows the livereload: https://chromewebstore.google.com/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei  plugin to listen to changes
      - 5005:5005 # Port 5005 makes the debugger available to the IDE
    depends_on:
      - mariadb 

  redis:
    image: docker.io/redis:7-alpine
    container_name: redis
    ports:
      - 6379:6379

  # Mariadb Service
  mariadb:
    image: docker.io/mariadb:11
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d:ro
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_MASTER_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_MASTER_DATABASE}
      TZ: Asia/Bangkok
      
  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin:5
    container_name: phpmyadmin
    # restart: always
    volumes:
      - ./docker/phpmyadmin/config/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
      - phpmyadmin_data:/var/www/html/
      - /sessions
    ports:
      - 8083:80
    environment:
      PMA_HOST: mariadb
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 50M
    depends_on:
      - mariadb

volumes:
  mariadb_data:
  phpmyadmin_data: