server:
    port:
        8082
spring:
    datasource:
        username: root
        password: 44332211
        url: jdbc:mariadb://mariadb:3306/movies
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
project:
    poster: posters/